import Header from "./(components)/Header";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <noscript className="text-4xl text-red-400 text-center font-extrabold">
          Javascript has been disabled in your browser.
        </noscript>
      </body>
    </html>
  );
}
